# Generated by Django 4.2.9 on 2024-01-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_avg_movie_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
